#!perl

use strict;
use FF;

for my $d (2..10) {
  for my $n (1 .. $d-1) {
    my $x = FF->new_from_rational($n, $d);
    printf "%2d/%2d   0.%s\n", $n, $d, join("", @$x);
  }
}

for (my $i = 2; $i < 1000000; $i *= 2) {
    my $x = FF->new_from_rational(1, $i);
    printf "%2d/%8d   0.%s    (%.40f)\n", 1, $i, join(" ", @$x), 1/$i;
}
