#!/usr/bin/env perl
# -*- cperl -*-

use strict;
use FF;

if (@ARGV == 1) {
  my @x = FF->new_from_real(@ARGV)->expansion;
  print "0.", display_expansion(@x), "\n";
}  elsif (@ARGV == 2) {
  my @x = FF->new_from_rational(@ARGV)->expansion;
  print "0.", display_expansion(@x), "\n";
} else {
  usage();
}

sub display_expansion {
  my @x = @_;
  my $j = (grep($_ > 9, @x) ? " " : "");
  join $j, @x;
}

sub usage {
  print STDERR "Usage:\tff 0.1435 # expand 0.1435\n\tff n d # expand rational n/d\n";
  exit 1;
}
